[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_donate = "G2tD9mUeKEQEfdTMseQqgxK7JrGB4DaJVbWZoYfRFgGK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
